#!/bin/sh

BLANK='#00000000'
CLEAR='#ffffff55'
DEFAULT='#00897bE6'
TEXT='#00897bE6'
WRONG='#880000bb'
VERIFYING='#00564dE6'

swaylock \
--inside-ver-color=$CLEAR     \
--ring-ver-color=$VERIFYING   \
\
--inside-wrong-color=$CLEAR   \
--ring-wrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--text-ver-color=$TEXT          \
--text-wrong-color=$TEXT          \
--layout-text-color=$TEXT         \
--key-hl-color=$WRONG         \
--bs-hl-color=$WRONG          \
\
# --clock                      \
# --indicator                  \
# --time-str="%H:%M:%S"        \
# --date-str="%A, %Y-%m-%d"       \
# --blur 9                     \
# --screen 1                   \
# --date-color=$TEXT           \
#--time-color=$TEXT           \
